version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev -- --host
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB=mongodb+srv://Saranraj:Docker123@mern-docker.yhv5p.mongodb.net/?retryWrites=true&w=majority&appName=Mern-Docker
    volumes:
      - ./server:/app
    command: npm start
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: